token: "MTM3Mjk1MzQ3NDk0MTA2MzI4OA.Gc_MPX.AhaliBIax_FD0Oo9CNT8KFbBzrQAhjhtYxTF50"
preferred-channel: "system"
guild-id: 1367617381165174984 # guild-id is not required, and not recomended for global use.